# ==================================================
# General parameters
# ==================================================

# NAME of this run
name: "exp85-generate-embeddings"
seed: 42

# dataset
dataset: "codraw"
dataset_path: "./data/CoDraw/codraw_train.h5"
valid_dataset_path: "./data/CoDraw/codraw_val.h5"
test_dataset_path: "./data/CoDraw/codraw_test.h5"
glove_path: "./data/misc/glove_codraw_iclevr.txt"

# run
batch_size: 50
num_workers: 2

# ==================================================
# Special parameters
# ==================================================

fork: "exp78"
model_path: "./results/experiments/exp78-pretrain-tirg/snapshots/codraw_pretrain_models_epoch_10.pth"

sentence_encoder_type: "bert"
text_dim: 768

save_root_dir: "./data/CoDraw/"